### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [xosecristo/pruebaSTARTPOINT#1]
Resultados: José Valle
Ciclo: 1

Problema 1: Python
- El archivo de entrada está fijo en el código, como buena práctica no debe existir nada fijo, no se puede probar
- Existen condiciones expuestas en el problema que no han sido cubiertas, favor de revisar a detalle todos los escenarios
- Al esperar que este sea el lenguaje de mayor dominios, se espera el uso de clases, manejo de excepciones y manejo como proyecto de python, uso de pip, etc

Problema 2: Python
- El archivo de entrada está fijo en el código, como buena práctica no debe existir nada fijo, no se puede probar
- Existen condiciones expuestas en el problema que no han sido cubiertas, favor de revisar a detalle todos los escenarios
- La solución del problema no es correcta, favor de revisar cómo se determina el ganador
- Al esperar que este sea el lenguaje de mayor dominios, se espera el uso de clases, manejo de excepciones y manejo como proyecto de python, uso de pip, etc

Nota: 
- En las regla 5 del problema se expone que se espera la solución de ambos en un lenguaje de mayor dominio y al menos 1 en un lenguaje que te gustaría aprender, en este caso solo he recibido los problemas resueltos en python

**Comment by xosecristo** [comment]
@nbxandresvejar  Se actualizó el repositorio basado en sus comentarios. 🐇
