### ISSUE TITLE
Prueba 2

### ISSUE THREAD

**Issue by nbxandresvejar** [xosecristo/pruebaSTARTPOINT#2]
Resultados: José Valle
Ciclo: 2

Problema 1: Python
Error al ejecutar programa: Revisar uso de caracteres, o especificar el encoding del archivo
File "main.py", line 40
SyntaxError: Non-ASCII character '\xc3' in file main.py on line 40, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Error al cargar módulo, aún cuando se realiza la instalación del modulo de python easygui este no puede ser ejecutado en ambiente linux.
Por favor revisar dependencia y/o agregar archivo de dependencias requirements.txt. Se puede hacer uso de argumentos para evitar el uso de un componente de terceros
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import easygui
ImportError: No module named easygui

Problema 2: Python
No se cubrieron las observaciones de la prueba 1. Van de nuevo
- El archivo de entrada está fijo en el código, como buena practica no debe existir nada fijo, no se puede probar
- Existen condiciones expuestas en el problema que no han sido cubiertas, favor de revisar a detalle todos los escenarios
- La solución del problema no es correcta, favor de revisar como se determina el ganador
- Al esperar que este sea el lenguaje de mayor dominios, se espera el uso de clases, manejo de excepciones y manejo como proyecto de python, uso de pip, etc

Problema 2: c#
- La solución del problema no es correcta, favor de revisar como se determina el ganador

**Comment by xosecristo** [comment]
@nbxandresvejar Se actualizó el Ejercicio 01 basado en los comentarios provistos. 

Respecto al ejercicio 02, el documento dice:
 _"Al terminar el juego quien gana es aquel que haya conseguido la mayor ventaja"_ 

... El programa genera correctamente un archivo con los datos estipulados en el documento. 

Cito: _"Esta línea contiene dos enteros, el primer entero es 1 o 2 indicando quien fue  el ganador, y el segundo entero es la ventaja con la que gana ese jugador"_ .
